name: Creating Environment
on:
    workflow_dispatch:
        inputs:
            environment:
                description: Environment Name
                required: true
                type: string
jobs:
    create-environment:
        runs-on: ubuntu-latest

        steps: 
            - name: 'Create Environment'
              run: |
                gh auth status
                gh repo view SpaceBoySpike/GA-Lab1
                echo "Creating Environment for: ${{ github.event.inputs.environment }}"
                curl -L \
                    -X PUT \
                    https://api.github.com/repos/${{ github.repository }}/environments/${{ github.event.inputs.environment }} \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \ 
