name: Creating Environment
on:
    workflow_dispatch:
        inputs:
            environment:
                description: Environment Name
                required: true
                type: string
jobs:
    create-environment:
        runs-on: ubuntu-latest

        steps: 
            - name: 'Create Environment'
              run: |
                echo "Creating Environment for: ${{ github.event.inputs.environment }}"
                curl -L \
                    -X PUT \
                    "https://api.github.com/repos/${{ github.repository }}/environments/${{ github.event.inputs.environment }}" \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}"
                echo curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/environments" | jq -r '.environments[].name'
