name: "Lab 1"
on:
  push
jobs:
  Build:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build
  Test:
    needs: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: "Install dependencies"
        run: npm ci

      - name: "Run tests"
        run: |
          echo "running tests..."
          npm test
          echo "running tests...done"
  Lint:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: "Install dependencies"
        run: npm ci

      - name: "Lint"
        run: |
          echo "linting code..."
          npm run lint
          echo "linting code...done"
  Issues:
    needs: Lint
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: See Issues
        run: echo "{{ issues }}"