name: Install Nginx in VM

on:
    workflow_dispatch:

jobs:
    install-nginx:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Install Nginx
              run: |
                az vm run-command invoke \
                    --command-id RunShellScript \
                    --name sp-vm-learn \
                    --resource-group vmss-sp-learning \
                    --scripts "sudo apt update && sudo apt install -y nginx"
            - name: Check Nginx Status
              run: |
                az vm run-command invoke \
                    --command-id RunShellScript \
                    --name sp-vm-learn \
                    --resource-group vmss-sp-learning \
                    --scripts "systemctl status nginx"